FROM python:3.11

WORKDIR /Users/aleksandrsichkar/Documents/sdet_task

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

CMD ["python", "-m" , "pytest", "--html=report.html", "test/"]